/// Quick reference guide for using Firestore in this app
/// 
/// For more details, see the specific class files:
/// - FirestoreDatasource: lib/data/dataresources/firestore_datasource.dart
/// - ExpenseModel: lib/data/models/expense_model.dart
/// - UserAccountModel: lib/data/models/user_account_model.dart

// import 'package:fully_cloud_sguard/data/repositories/repository_provider.dart';
// import 'package:fully_cloud_sguard/domain/entities/expense.dart';
// import 'package:fully_cloud_sguard/domain/entities/user_account.dart';

/// USAGE EXAMPLES
/// 
/// Example 1: Add a new expense
/// ```dart
/// final repositories = RepositoryProvider();
/// 
/// final newExpense = Expense(
///   id: '',  // Will be generated by Firestore
///   userId: 'user123',
///   category: 'Food',
///   amount: 25.50,
///   description: 'Lunch',
///   date: DateTime.now(),
///   createdAt: DateTime.now(),
/// );
/// 
/// final expenseId = await repositories.expenseRepository.addExpense(newExpense);
/// print('Expense added with ID: $expenseId');
/// ```
/// 
/// Example 2: Get all expenses for a user
/// ```dart
/// final repositories = RepositoryProvider();
/// 
/// final expenses = await repositories.expenseRepository.getUserExpenses('user123');
/// for (var expense in expenses) {
///   print('${expense.category}: \$${expense.amount}');
/// }
/// ```
/// 
/// Example 3: Stream expenses for real-time updates
/// ```dart
/// final repositories = RepositoryProvider();
/// 
/// repositories.expenseRepository.streamUserExpenses('user123').listen((expenses) {
///   print('Expenses updated: ${expenses.length} items');
/// });
/// ```
/// 
/// Example 4: Get expenses for a date range
/// ```dart
/// final repositories = RepositoryProvider();
/// final startDate = DateTime(2026, 1, 1);
/// final endDate = DateTime(2026, 3, 31);
/// 
/// final expenses = await repositories.expenseRepository.getExpensesByDateRange(
///   'user123',
///   startDate,
///   endDate,
/// );
/// ```
/// 
/// Example 5: Save user account
/// ```dart
/// final repositories = RepositoryProvider();
/// 
/// final user = UserAccount(
///   uid: 'user123',
///   email: 'user@example.com',
///   name: 'John Doe',
///   balance: 1000.0,
///   createdAt: DateTime.now(),
///   updatedAt: DateTime.now(),
/// );
/// 
/// await repositories.userRepository.saveUserAccount(user);
/// ```
/// 
/// Example 6: Update user balance
/// ```dart
/// final repositories = RepositoryProvider();
/// 
/// await repositories.userRepository.updateUserBalance('user123', 950.0);
/// ```
/// 
/// FIRESTORE STRUCTURE:
/// ```
/// users/
///   {uid}/
///     - email: string
///     - name: string
///     - balance: number
///     - createdAt: string (ISO 8601)
///     - updatedAt: string (ISO 8601)
///     expenses/
///       {expenseId}/
///         - userId: string
///         - category: string
///         - amount: number
///         - description: string
///         - date: string (ISO 8601)
///         - createdAt: string (ISO 8601)
/// ```

void usageGuide() {
  // This file is just documentation, ignore this function
}
